version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5433:5433"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecus
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET_NAME=ecus
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      # please generate with `openssl rand -base64 32`
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GITHUB_ORGANIZATION=${AUTH_GITHUB_ORGANIZATION}
    depends_on:
      - db
      - minio

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add ecus-storage http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb ecus-storage/ecus;
      /usr/bin/mc anonymous set public ecus-storage/ecus;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
